# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_housing', '0002_auto_20151215_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.TextField(default='Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
    ]
